"""empty message

Revision ID: 38d17971ab3b
Revises: ddf3072ef4bd
Create Date: 2018-04-24 17:17:35.902475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d17971ab3b'
down_revision = 'ddf3072ef4bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'follows_userID_fkey', 'follows', type_='foreignkey')
    op.drop_constraint(u'follows_followerID_fkey', 'follows', type_='foreignkey')
    op.drop_constraint(u'likes_userID_fkey', 'likes', type_='foreignkey')
    op.drop_constraint(u'likes_postID_fkey', 'likes', type_='foreignkey')
    op.drop_constraint(u'posts_userID_fkey', 'posts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'posts_userID_fkey', 'posts', 'users', ['userID'], ['id'])
    op.create_foreign_key(u'likes_postID_fkey', 'likes', 'posts', ['postID'], ['id'])
    op.create_foreign_key(u'likes_userID_fkey', 'likes', 'users', ['userID'], ['id'])
    op.create_foreign_key(u'follows_followerID_fkey', 'follows', 'users', ['followerID'], ['id'])
    op.create_foreign_key(u'follows_userID_fkey', 'follows', 'users', ['userID'], ['id'])
    # ### end Alembic commands ###
