"""empty message

Revision ID: ddf3072ef4bd
Revises: a15a512888f7
Create Date: 2018-04-23 21:42:19.559871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddf3072ef4bd'
down_revision = 'a15a512888f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(length=80), nullable=True))
    op.drop_constraint(u'users_userName_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'userName')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstName', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lastName', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('userName', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint(u'users_userName_key', 'users', ['userName'])
    op.drop_column('users', 'username')
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
